console.log("My First Console Project");
var first_name= "Sara";
var last_name= "Manesia";
var full_name= first_name.concat(last_name);
console.log(full_name);
var a=20;
console.log(a);
var b=30;
console.log(b);
var add=a+b;
console.log(add);
var multi=a*b;
console.log(multi);
